### PR TITLE
fixed bug in conversion of amount to kobo equivalent

### PR DESCRIPTION
**Pull request by majirieyowel**
Found a little bug while converting amount to kobo

### CODE REVIEW

**Comment by walosha** [comment]
The props.amount was not properly destructured.

It should have been :

` const {amount} = props`

**Review by mosoakinyemi — APPROVED** [review]
👍🏼

**Comment by mosoakinyemi** [comment]
cc @just1and0

**Comment by mosoakinyemi** [comment]
Thanks for this boss, it's coming with v4.0.0-rc1

**Pull request closed without merging**
