### PR TITLE
Add KES to Currency Type

### PR DESCRIPTION
**Pull request by maukoese**
Add KES to Currency Types since Paystack is now supported in Kenya.

### CODE REVIEW

**Review by just1and0 — APPROVED** [review]
LGTM

**Review by just1and0 — APPROVED** [review]
LGTM

**Review by just1and0 — APPROVED** [review]

**Review by just1and0 — APPROVED** [review]

**Comment by just1and0** [comment]
@all-contributors add @maukoese for docs

**Comment by maukoese** [comment]
Thank you so much!

**Pull request merged**
