### PR TITLE
Disabled webview caching

### PR DESCRIPTION
**Pull request by majirieyowel**

### CODE REVIEW

**Review by mosoakinyemi — APPROVED** [review]
Thanks for this man!

**Comment by mosoakinyemi** [comment]
cc @just1and0

**Review by mosoakinyemi — COMMENTED** [review]
Thanks @majirieyowel for this PR🙏🏼

cc @rajibola this should also come with the next patch as an improvement

**Comment by just1and0** [comment]
@all-contributors please add @majirieyowel for code

**Pull request merged**
