### PR TITLE
Update Installation guide and Include Types for Typescript

### PR DESCRIPTION
**Pull request by Darkace01**
Update Readme installation guide, Refactor Paystack component to adhere to TypeScript types

### CODE REVIEW

**Comment by just1and0** [comment]
We currently restructured our codebase, can you refactor this and open the PR again ?

**Comment by Darkace01** [comment]
This pull request includes several updates to the `README.md` file and some changes in the `src/paystack.tsx` file to improve documentation and code clarity.

### Documentation Enhancements:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R75): Enhanced the introduction with a more detailed description and added a screenshot for better visual appeal.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R75): Updated the installation instructions to separate basic React Native and Expo installations for better clarity.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L99-R141): Renamed the API section for better readability and updated the table format for the API reference.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L119): Minor formatting changes and additional setup instructions to ensure smooth installation.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L183-R222): Added a roadmap section to outline future improvements and goals.

### Codebase Improvements:

* [`src/paystack.tsx`](diffhunk://#diff-559fbb04cd0d655ad3a129d1ad2d8c94b3df2f090fd6d0e05f759043190d254dL1-R6): Added semicolons to improve code consistency and readability.
* [`src/paystack.tsx`](diffhunk://#diff-559fbb04cd0d655ad3a129d1ad2d8c94b3df2f090fd6d0e05f759043190d254dL19-R19): Changed the `channels` prop to use the `PaymentChannels` type for better type safety.
* [`src/paystack.tsx`](diffhunk://#diff-559fbb04cd0d655ad3a129d1ad2d8c94b3df2f090fd6d0e05f759043190d254dL28-R29): Adjusted the `PayStackProps` type usage in the `Paystack` component for better type handling.
* [`src/paystack.tsx`](diffhunk://#diff-559fbb04cd0d655ad3a129d1ad2d8c94b3df2f090fd6d0e05f759043190d254dL152-R152): Typed the `onMessage` event handler parameter as `any` to avoid type errors.
* [`src/paystack.tsx`](diffhunk://#diff-559fbb04cd0d655ad3a129d1ad2d8c94b3df2f090fd6d0e05f759043190d254dL174-L177): Removed unnecessary new lines at the end of the file for cleaner code.

**Comment by just1and0** [comment]
@Darkace01 thanks for the improvement, this PR is not following the new folder structure, it also being pushed to master which is no longer in use as such it can't be merged. I will close this now and ask you make a new PR to main.

**Comment by Darkace01** [comment]
Thanks I will check it out and make the necessary updates

**Pull request closed without merging**
