### PR TITLE
Expose the metadata props option

### PR DESCRIPTION
**Pull request by saidiadegoke**
I added some scripts to expose the metadata option in order to accommodate as many options as possible when I noticed I couldn't add custom data apart from the display name, email, and phone.

### CODE REVIEW

**Comment by mosoakinyemi** [comment]
Thanks for this PR @saidiadegoke 🙏🏼
cc @rajibola this changes should come with the next patch for v4.0.0-rc1

**Comment by just1and0** [comment]
@mosho we're having a bit of issue with this PR, can we resolve it so we include in the next patch for V4

**Comment by saidiadegoke** [comment]
Thanks for reaching out. I'll resolve the issue asap. Thanks.

**Comment by mosoakinyemi** [comment]
Yeah, either @saidiadegoke updates the PR or I'll add that as a patch to v4.0.0.

Seems @saidiadegoke will make an update 🙂

Will check back on this.

**Comment by mosoakinyemi** [comment]
@saidiadegoke thanks man, one issue tho.
Seems you've not updated your local repo...hence, your changes are reflecting the old code/structure.

Kindly repull/rebase from the master branch and redo your changes😉
Thanks.

**Comment by just1and0** [comment]
@saidiadegoke just checking in if this is ready.

**Comment by saidiadegoke** [comment]
Update has now been made.

**Review by tons613 — APPROVED** [review]

**Comment by saidiadegoke** [comment]
I added the requested changes. The `metadata` option has been added to the `PaystackProps` type. Kindly take a look.

**Comment by kazeemOnis** [comment]
Any luck here @just1and0 @saidiadegoke?

**Comment by sleekLancelot** [comment]
hi @just1and0 @mosoakinyemi 
Looks like this package is still our only hope for handling paystack payment with react native. Also it seems @saidiadegoke updated the PR. Please can you check again, i could pick it up if you need some things changed again.

**Comment by just1and0** [comment]
> hi @just1and0 @mosoakinyemi 
> 
> Looks like this package is still our only hope for handling paystack payment with react native. Also it seems @saidiadegoke updated the PR. Please can you check again, i could pick it up if you need some things changed again. 

Well this isn’t the only package 😅 there’s [Ortho Finance](https://tryortho.co). But I will look into this and see how we can include this.

**Comment by sleekLancelot** [comment]
> > hi @just1and0 @mosoakinyemi
> > Looks like this package is still our only hope for handling paystack payment with react native. Also it seems @saidiadegoke updated the PR. Please can you check again, i could pick it up if you need some things changed again.
> 
> Well this isn’t the only package 😅 there’s [Ortho Finance](https://tryortho.co). But I will look into this and see how we can include this.

I checked out ortho finance, the pages in their documentation are pretty much empty, hoping you would have time to review this PR again.

**Comment by just1and0** [comment]
re

**Comment by just1and0** [comment]
Resolved on #185

**Pull request closed without merging**
