### PR TITLE
Added the subaccount/payment split feature

### PR DESCRIPTION
**Pull request by opmat**
Added the subaccount/payment split feature as documented by Paystack

### CODE REVIEW

**Comment by GenerousDev** [comment]
@opmat @just1and0 Please why was this not merged.

**Review by just1and0 — APPROVED** [review]
LGTM

**Comment by just1and0** [comment]
@opmat Thanks for making these changes.

**Comment by just1and0** [comment]
@all-contributors please add @opmat  for code

**Pull request merged**
